### ISSUE TITLE
When adding new roles to aws-auth, rolearn should be used instead of userarn

### ISSUE THREAD

**Issue by Markonick** [cookiecutter-openedx/cookiecutter-openedx-devops#60]
**Describe the bug**
Adding a role in map_roles inside stacks/service/kubernetes/terragrunt.hcl results in the following error:
```

│ Error: Invalid value for input variable
│ 
│   on variables.tf line 98:
│   98: variable "map_roles" {
│ 
│ Unsuitable value for var.map_roles set using the TF_VAR_map_roles
│ environment variable: element 0: attribute "userarn" is required.
```

**Workflow**
To recreate this bug, let me give some context:

I needed to add a CI role (not user) for GitHub actions to be able to talk to the EKS cluster.
My role looks like this:
```
map_roles = [
    {
      rolearn  = "arn:aws:iam::${local.account_id}:role/GitHubAction-AssumeRoleWithAction"
      username = "AWSSession_GitHub"
      groups   = ["system:masters"]
    },
  ]
```
When I tried applying my change following the build sequence:

```
cd …/openedx_devops/terraform/stacks/service
terragrunt run-all init

cd kubernetes
terragrunt apply -target module.cookiecutter_meta
terragrunt apply
```

the error described above occurs.

**Expected behavior**
The error above should not occur. 

**Additional context**
According to https://registry.terraform.io/modules/aidanmelen/eks-auth/aws/1.0.0#:~:text=no-,map_roles,-Additional%20IAM%20roles, rolearn should be used instead.

**Comment by lpm0073** [comment]
Thanks for reporting this @Markonick . You might consider creating a PR for this, noting the following:
- there's hook for map_roles[] located [here](https://github.com/cookiecutter-openedx/cookiecutter-openedx-devops/blob/main/%7B%7Bcookiecutter.github_repo_name%7D%7D/terraform/stacks/%7B%7Bcookiecutter.global_platform_shared_resource_identifier%7D%7D/kubernetes/terragrunt.hcl#L76) which i've yet to code simply for lack of a need on any my projects so far.
- you can refer to the code pattern for map_user[], which ends [here](https://github.com/cookiecutter-openedx/cookiecutter-openedx-devops/blob/main/%7B%7Bcookiecutter.github_repo_name%7D%7D/terraform/stacks/modules/kubernetes/main.tf#L58)
- map_roles[] is already declared in [variable.tf](https://github.com/cookiecutter-openedx/cookiecutter-openedx-devops/blob/main/%7B%7Bcookiecutter.github_repo_name%7D%7D/terraform/stacks/modules/kubernetes/variables.tf#L66)

As an interim workaround you might consider editing kube-system/aws-auth:configMap directly, which looks approximately like the following:

<img width="1068" alt="Screenshot 2023-08-23 at 7 13 36" src="https://github.com/cookiecutter-openedx/cookiecutter-openedx-devops/assets/1178819/423ac3bb-6f50-4db7-afa0-b0d15ab34f5f">

**Comment by Markonick** [comment]
Sorry about this, my first time actually trying to contribute in an open-source project. I already opened a pull-request but must have done something wrong: https://github.com/cookiecutter-openedx/cookiecutter-openedx-devops/pull/61 (couldn't find how to assign a reviewer).

As for your solution, yep, I edited it in `aws-auth `on Lens so this doesn't block me.

**Comment by lpm0073** [comment]
Closing this via [PR #61](https://github.com/cookiecutter-openedx/cookiecutter-openedx-devops/pull/61)
